stop-words = "data/lemur-stopwords.txt"
prefix = "data/"

dataset = "cranfield"
corpus = "tutorial.toml"
index = "cranfield-idx"

query-judgements = "data/cranfield/cranfield-qrels.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"
